# Use an official MongoDB image as the base image
FROM mongo:5.0.15

# Optionally, you can set environment variables and perform other configurations here.
# For example, you can set the database directory if needed:
# ENV MONGO_DATA_DIR=/data/db

# Expose the default MongoDB port (27017)
EXPOSE 27017

# Define the command to start MongoDB when the container runs
CMD ["mongod"]
